const { Employee } = require('../models');

const employeeData = [
  {
    first_name: 'Josie',
    last_name: 'Haney',
    role_id: 1,
    primary_venue: 1,
  },
  {
    first_name: 'Keaton',
    last_name: 'Fowler',
    role_id: 1,
    primary_venue: 1,
  },
  {
    first_name: 'Leandro',
    last_name: 'Castro',
    role_id: 1,
    primary_venue: 2,
  },
  {
    first_name: 'Wade',
    last_name: 'Page',
    role_id: 1,
    primary_venue: 2,
  },
  {
    first_name: 'Aditya',
    last_name: 'Woods',
    role_id: 1,
    primary_venue: 2,
  },
  {
    first_name: 'Derick',
    last_name: 'Ashley',
    role_id: 1,
    primary_venue: 2,
  },
  {
    first_name: 'Leila',
    last_name: 'Foley',
    role_id: 1,
    primary_venue: 3,
  },
  {
    first_name: 'Denisse',
    last_name: 'Hobbs',
    role_id: 1,
    primary_venue: 3,
  },
  {
    first_name: 'Juliette',
    last_name: 'Stanton',
    role_id: 1,
    primary_venue: 3,
  },
  {
    first_name: 'Kaitlin',
    last_name: 'Lyons',
    role_id: 1,
    primary_venue: 3,
  },
  {
    first_name: 'Brayden',
    last_name: 'Hebert',
    role_id: 1,
    primary_venue: 3,
  },
  {
    first_name: 'Trenton',
    last_name: 'Pace',
    role_id: 1,
    primary_venue: 3,
  },
  {
    first_name: 'Simeon',
    last_name: 'Hancock',
    role_id: 2,
    primary_venue: 1,
  },
  {
    first_name: 'Kaylie',
    last_name: 'Benson',
    role_id: 2,
    primary_venue: 1,
  },
  {
    first_name: 'Kaley',
    last_name: 'Huff',
    role_id: 2,
    primary_venue: 1,
  },
  {
    first_name: 'Jairo',
    last_name: 'Bates',
    role_id: 2,
    primary_venue: 2,
  },
  {
    first_name: 'Landyn',
    last_name: 'Peters',
    role_id: 2,
    primary_venue: 2,
  },
  {
    first_name: 'Will',
    last_name: 'Washington',
    role_id: 2,
    primary_venue: 2,
  },
  {
    first_name: 'Maximilian',
    last_name: 'Richards',
    role_id: 2,
    primary_venue: 3,
  },
  {
    first_name: 'Courtney',
    last_name: 'Owens',
    role_id: 2,
    primary_venue: 3,
  },
  {
    first_name: 'Santino',
    last_name: 'Dougherty',
    role_id: 2,
    primary_venue: 3,
  },
  {
    first_name: 'Natasha',
    last_name: 'Best',
    role_id: 3,
    primary_venue: 1,
  },
  {
    first_name: 'Kaley',
    last_name: 'Carrillo',
    role_id: 3,
    primary_venue: 1,
  },
  {
    first_name: 'Jaslene',
    last_name: 'Guzman',
    role_id: 3,
    primary_venue: 2,
  },
  {
    first_name: 'Jax',
    last_name: 'Luna',
    role_id: 3,
    primary_venue: 2,
  },
  {
    first_name: 'Tobias',
    last_name: 'Ayala',
    role_id: 3,
    primary_venue: 3,
  },
  {
    first_name: 'Denise',
    last_name: 'Zavala',
    role_id: 3,
    primary_venue: 3,
  },
  {
    first_name: 'Madelynn',
    last_name: 'Mcpherson',
    role_id: 4,
    primary_venue: 1,
  },
  {
    first_name: 'Lillie',
    last_name: 'Tapia',
    role_id: 4,
    primary_venue: 1,
  },
  {
    first_name: 'Carson',
    last_name: 'Randall',
    role_id: 4,
    primary_venue: 2,
  },
  {
    first_name: 'Kadence',
    last_name: 'Koch',
    role_id: 4,
    primary_venue: 2,
  },
  {
    first_name: 'Gemma',
    last_name: 'Ellis',
    role_id: 4,
    primary_venue: 3,
  },
  {
    first_name: 'Ace',
    last_name: 'Murillo',
    role_id: 4,
    primary_venue: 3,
  },
  {
    first_name: 'Jax',
    last_name: 'Castillo',
    role_id: 5,
    primary_venue: 1,
  },
  {
    first_name: 'Josh',
    last_name: 'Livingston',
    role_id: 5,
    primary_venue: 1,
  },
  {
    first_name: 'Ernest',
    last_name: 'Booker',
    role_id: 5,
    primary_venue: 1,
  },
  {
    first_name: 'Dana',
    last_name: 'Miles',
    role_id: 5,
    primary_venue: 2,
  },
  {
    first_name: 'Cora',
    last_name: 'Steele',
    role_id: 5,
    primary_venue: 2,
  },
  {
    first_name: 'Rodney',
    last_name: 'Olson',
    role_id: 5,
    primary_venue: 2,
  },
  {
    first_name: 'Alannah',
    last_name: 'Richards',
    role_id: 5,
    primary_venue: 3,
  },
  {
    first_name: 'Maryjane',
    last_name: 'Leblanc',
    role_id: 5,
    primary_venue: 3,
  },
  {
    first_name: 'Cade',
    last_name: 'Klein',
    role_id: 5,
    primary_venue: 3,
  },
  {
    first_name: 'Zackery',
    last_name: 'Howell',
    role_id: 6,
    primary_venue: 3,
  },
  {
    first_name: 'Tessa',
    last_name: 'Shea',
    role_id: 6,
    primary_venue: 3,
  },
  {
    first_name: 'Mike',
    last_name: 'Fletcher',
    role_id: 6,
    primary_venue: 3,
  },
  {
    first_name: 'Alejandro',
    last_name: 'Floyd',
    role_id: 6,
    primary_venue: 3,
  },
  {
    first_name: 'Mohammad',
    last_name: 'Oneill',
    role_id: 7,
    primary_venue: 1,
  },
  {
    first_name: 'Elias',
    last_name: 'Mcdaniel',
    role_id: 7,
    primary_venue: 1,
  },
  {
    first_name: 'Angie',
    last_name: 'Booth',
    role_id: 7,
    primary_venue: 1,
  },
  {
    first_name: 'Jonas',
    last_name: 'Alvarez',
    role_id: 7,
    primary_venue: 2,
  },
  {
    first_name: 'Jonas',
    last_name: 'Cordova',
    role_id: 7,
    primary_venue: 2,
  },
  {
    first_name: 'Daisy',
    last_name: 'Pacheco',
    role_id: 7,
    primary_venue: 2,
  },
  {
    first_name: 'Sandra',
    last_name: 'Cameron',
    role_id: 7,
    primary_venue: 3,
  },
  {
    first_name: 'Brooklynn',
    last_name: 'Benjamin',
    role_id: 7,
    primary_venue: 3,
  },
  {
    first_name: 'Nash',
    last_name: 'Randall',
    role_id: 7,
    primary_venue: 3,
  },
  {
    first_name: 'Dayanara',
    last_name: 'Barker',
    role_id: 8,
    primary_venue: 1,
  },
  {
    first_name: 'Carsen',
    last_name: 'Higgins',
    role_id: 8,
    primary_venue: 1,
  },
  {
    first_name: 'Madden',
    last_name: 'Li',
    role_id: 8,
    primary_venue: 1,
  },
  {
    first_name: 'Julius',
    last_name: 'Compton',
    role_id: 8,
    primary_venue: 1,
  },
  {
    first_name: 'Jayden',
    last_name: 'Shepard',
    role_id: 8,
    primary_venue: 1,
  },
  {
    first_name: 'Pablo',
    last_name: 'Hoffman',
    role_id: 8,
    primary_venue: 2,
  },
  {
    first_name: 'Manuel',
    last_name: 'Manning',
    role_id: 8,
    primary_venue: 2,
  },
  {
    first_name: 'Arthur',
    last_name: 'Wilkerson',
    role_id: 8,
    primary_venue: 2,
  },
  {
    first_name: 'Brianna',
    last_name: 'Charles',
    role_id: 8,
    primary_venue: 2,
  },
  {
    first_name: 'Linda',
    last_name: 'Branch',
    role_id: 8,
    primary_venue: 2,
  },
  {
    first_name: 'Nash',
    last_name: 'Dalton',
    role_id: 8,
    primary_venue: 2,
  },
  {
    first_name: 'Dahlia',
    last_name: 'Krueger',
    role_id: 8,
    primary_venue: 2,
  },
  {
    first_name: 'Donavan',
    last_name: 'Decker',
    role_id: 8,
    primary_venue: 2,
  },
  {
    first_name: 'Lilianna',
    last_name: 'Dougherty',
    role_id: 8,
    primary_venue: 2,
  },
  {
    first_name: 'Maximillian',
    last_name: 'Stevenson',
    role_id: 8,
    primary_venue: 2,
  },
  {
    first_name: 'Janiya',
    last_name: 'Watts',
    role_id: 8,
    primary_venue: 3,
  },
  {
    first_name: 'Devan',
    last_name: 'Montes',
    role_id: 8,
    primary_venue: 3,
  },
  {
    first_name: 'April',
    last_name: 'Mendez',
    role_id: 8,
    primary_venue: 3,
  },
  {
    first_name: 'Deven',
    last_name: 'Burnett',
    role_id: 8,
    primary_venue: 3,
  },
  {
    first_name: 'Davion',
    last_name: 'Wu',
    role_id: 8,
    primary_venue: 3,
  },
  {
    first_name: 'Lena',
    last_name: 'Aguirre',
    role_id: 8,
    primary_venue: 3,
  },
  {
    first_name: 'Joyce',
    last_name: 'Curtis',
    role_id: 8,
    primary_venue: 3,
  },
  {
    first_name: 'Lina',
    last_name: 'Rosales',
    role_id: 8,
    primary_venue: 3,
  },
  {
    first_name: 'Nia',
    last_name: 'Schneider',
    role_id: 8,
    primary_venue: 3,
  },
  {
    first_name: 'Cailyn',
    last_name: 'Chandler',
    role_id: 8,
    primary_venue: 3,
  },
  {
    first_name: 'Roger',
    last_name: 'Hines',
    role_id: 8,
    primary_venue: 3,
  },
  {
    first_name: 'Bella',
    last_name: 'Coleman',
    role_id: 8,
    primary_venue: 3,
  },
  {
    first_name: 'Tomas',
    last_name: 'Reed',
    role_id: 8,
    primary_venue: 3,
  },
  {
    first_name: 'Priscilla',
    last_name: 'Shelton',
    role_id: 8,
    primary_venue: 3,
  },
  {
    first_name: 'Payton',
    last_name: 'Montoya',
    role_id: 8,
    primary_venue: 3,
  },
  {
    first_name: 'Mia',
    last_name: 'Holt',
    role_id: 9,
    primary_venue: 3,
  },
  {
    first_name: 'Amaris',
    last_name: 'Carey',
    role_id: 10,
    primary_venue: 3,
  },
  {
    first_name: 'Finn',
    last_name: 'Dodson',
    role_id: 10,
    primary_venue: 3,
  },
  {
    first_name: 'Ruben',
    last_name: 'Good',
    role_id: 10,
    primary_venue: 3,
  },
  {
    first_name: 'Moises',
    last_name: 'Lester',
    role_id: 10,
    primary_venue: 3,
  },
  {
    first_name: 'Miracle',
    last_name: 'Spencer',
    role_id: 11,
    primary_venue: 1,
  },
  {
    first_name: 'Koen',
    last_name: 'Frank',
    role_id: 11,
    primary_venue: 1,
  },
  {
    first_name: 'Darwin',
    last_name: 'Dillon',
    role_id: 11,
    primary_venue: 1,
  },
  {
    first_name: 'Adrianna',
    last_name: 'Curry',
    role_id: 11,
    primary_venue: 1,
  },
  {
    first_name: 'Damien',
    last_name: 'Key',
    role_id: 11,
    primary_venue: 1,
  },
  {
    first_name: 'Adolfo',
    last_name: 'Mcmahon',
    role_id: 11,
    primary_venue: 2,
  },
  {
    first_name: 'Alexus',
    last_name: 'Collins',
    role_id: 11,
    primary_venue: 2,
  },
  {
    first_name: 'Sheldon',
    last_name: 'Norman',
    role_id: 11,
    primary_venue: 2,
  },
  {
    first_name: 'Cooper',
    last_name: 'Green',
    role_id: 11,
    primary_venue: 2,
  },
  {
    first_name: 'Madeleine',
    last_name: 'Rose',
    role_id: 11,
    primary_venue: 2,
  },
  {
    first_name: 'Perla',
    last_name: 'Acosta',
    role_id: 11,
    primary_venue: 2,
  },
  {
    first_name: 'Kailee',
    last_name: 'Bender',
    role_id: 11,
    primary_venue: 2,
  },
  {
    first_name: 'Aniya',
    last_name: 'Bauer',
    role_id: 11,
    primary_venue: 2,
  },
  {
    first_name: 'Kyle',
    last_name: 'Mendez',
    role_id: 11,
    primary_venue: 2,
  },
  {
    first_name: 'Carmelo',
    last_name: 'Oneal',
    role_id: 11,
    primary_venue: 2,
  },
  {
    first_name: 'Jacoby',
    last_name: 'Villarreal',
    role_id: 11,
    primary_venue: 2,
  },
  {
    first_name: 'Selena',
    last_name: 'Keller',
    role_id: 11,
    primary_venue: 2,
  },
  {
    first_name: 'Jaydan',
    last_name: 'Benitez',
    role_id: 11,
    primary_venue: 2,
  },
  {
    first_name: 'Ashton',
    last_name: 'Evans',
    role_id: 11,
    primary_venue: 2,
  },
  {
    first_name: 'Braelyn',
    last_name: 'Raymond',
    role_id: 11,
    primary_venue: 2,
  },
  {
    first_name: 'Tristen',
    last_name: 'Ingram',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Camila',
    last_name: 'Weaver',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Briana',
    last_name: 'Dominguez',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Finley',
    last_name: 'Burns',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Sincere',
    last_name: 'Galloway',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Elianna',
    last_name: 'Tate',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Yamilet',
    last_name: 'Nash',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Travis',
    last_name: 'Byrd',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Turner',
    last_name: 'Santiago',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Angie',
    last_name: 'Pearson',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Jacob',
    last_name: 'Bentley',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Kristen',
    last_name: 'Pham',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Manuel',
    last_name: 'Carroll',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Deja',
    last_name: 'Blanchard',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Rory',
    last_name: 'Fox',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Steve',
    last_name: 'Atkins',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Selina',
    last_name: 'Guerrero',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Davis',
    last_name: 'Irwin',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Paul',
    last_name: 'Bridges',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Arabella',
    last_name: 'Rich',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Carmelo',
    last_name: 'Wang',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Valentina',
    last_name: 'Marshall',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Brent',
    last_name: 'Singh',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Amiya',
    last_name: 'Shea',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Oliver',
    last_name: 'Briggs',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Ezekiel',
    last_name: 'Graham',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Rhianna',
    last_name: 'Pacheco',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Gustavo',
    last_name: 'Rivas',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Finnegan',
    last_name: 'Freeman',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Ayden',
    last_name: 'Carr',
    role_id: 11,
    primary_venue: 3,
  },
  {
    first_name: 'Holden',
    last_name: 'Hodge',
    role_id: 12,
    primary_venue: 1,
  },
  {
    first_name: 'Myla',
    last_name: 'Rios',
    role_id: 12,
    primary_venue: 1,
  },
  {
    first_name: 'Aleah',
    last_name: 'Ryan',
    role_id: 12,
    primary_venue: 1,
  },
  {
    first_name: 'Aracely',
    last_name: 'Maynard',
    role_id: 12,
    primary_venue: 1,
  },
  {
    first_name: 'Jayden',
    last_name: 'Reynolds',
    role_id: 12,
    primary_venue: 1,
  },
  {
    first_name: 'Kiana',
    last_name: 'Salazar',
    role_id: 12,
    primary_venue: 1,
  },
  {
    first_name: 'Angeline',
    last_name: 'Navarro',
    role_id: 12,
    primary_venue: 1,
  },
  {
    first_name: 'Rihanna',
    last_name: 'Ruiz',
    role_id: 12,
    primary_venue: 1,
  },
  {
    first_name: 'Kasen',
    last_name: 'Mcbride',
    role_id: 12,
    primary_venue: 1,
  },
  {
    first_name: 'Frida',
    last_name: 'Gill',
    role_id: 12,
    primary_venue: 1,
  },
  {
    first_name: 'Joshua',
    last_name: 'Maxwell',
    role_id: 12,
    primary_venue: 2,
  },
  {
    first_name: 'Belen',
    last_name: 'Wade',
    role_id: 12,
    primary_venue: 2,
  },
  {
    first_name: 'Noah',
    last_name: 'Thompson',
    role_id: 12,
    primary_venue: 2,
  },
  {
    first_name: 'Alexis',
    last_name: 'Sanders',
    role_id: 12,
    primary_venue: 2,
  },
  {
    first_name: 'Finley',
    last_name: 'Glenn',
    role_id: 12,
    primary_venue: 2,
  },
  {
    first_name: 'Leilani',
    last_name: 'Young',
    role_id: 12,
    primary_venue: 2,
  },
  {
    first_name: 'Trey',
    last_name: 'Ramos',
    role_id: 12,
    primary_venue: 2,
  },
  {
    first_name: 'Steve',
    last_name: 'Peters',
    role_id: 12,
    primary_venue: 2,
  },
  {
    first_name: 'Michael',
    last_name: 'Carter',
    role_id: 12,
    primary_venue: 2,
  },
  {
    first_name: 'Dean',
    last_name: 'Mays',
    role_id: 12,
    primary_venue: 2,
  },
  {
    first_name: 'Angelique',
    last_name: 'Chaney',
    role_id: 12,
    primary_venue: 2,
  },
  {
    first_name: 'Zoey',
    last_name: 'Benton',
    role_id: 12,
    primary_venue: 2,
  },
  {
    first_name: 'Maryjane',
    last_name: 'Jacobs',
    role_id: 12,
    primary_venue: 2,
  },
  {
    first_name: 'Prince',
    last_name: 'Woods',
    role_id: 12,
    primary_venue: 2,
  },
  {
    first_name: 'Asa',
    last_name: 'Harvey',
    role_id: 12,
    primary_venue: 2,
  },
  {
    first_name: 'Devon',
    last_name: 'Hayden',
    role_id: 12,
    primary_venue: 3,
  },
  {
    first_name: 'Parker',
    last_name: 'Wiley',
    role_id: 12,
    primary_venue: 3,
  },
  {
    first_name: 'Henry',
    last_name: 'Lucero',
    role_id: 12,
    primary_venue: 3,
  },
  {
    first_name: 'Virginia',
    last_name: 'Weaver',
    role_id: 12,
    primary_venue: 3,
  },
  {
    first_name: 'Colin',
    last_name: 'Koch',
    role_id: 12,
    primary_venue: 3,
  },
  {
    first_name: 'Madison',
    last_name: 'Montgomery',
    role_id: 12,
    primary_venue: 3,
  },
  {
    first_name: 'Urijah',
    last_name: 'Keith',
    role_id: 12,
    primary_venue: 3,
  },
  {
    first_name: 'Tyshawn',
    last_name: 'Patel',
    role_id: 12,
    primary_venue: 3,
  },
  {
    first_name: 'Juliet',
    last_name: 'Buck',
    role_id: 12,
    primary_venue: 3,
  },
  {
    first_name: 'Terrance',
    last_name: 'Clark',
    role_id: 12,
    primary_venue: 3,
  },
  {
    first_name: 'Destiny',
    last_name: 'Vaughn',
    role_id: 12,
    primary_venue: 3,
  },
  {
    first_name: 'Bernard',
    last_name: 'White',
    role_id: 12,
    primary_venue: 3,
  },
  {
    first_name: 'Lily',
    last_name: 'Herring',
    role_id: 12,
    primary_venue: 3,
  },
  {
    first_name: 'Mayra',
    last_name: 'Cooley',
    role_id: 12,
    primary_venue: 3,
  },
  {
    first_name: 'Uriah',
    last_name: 'Greene',
    role_id: 12,
    primary_venue: 3,
  },
  {
    first_name: 'Kylan',
    last_name: 'Gonzalez',
    role_id: 12,
    primary_venue: 3,
  },
  {
    first_name: 'Branden',
    last_name: 'Ruiz',
    role_id: 12,
    primary_venue: 3,
  },
  {
    first_name: 'Yahir',
    last_name: 'Brown',
    role_id: 12,
    primary_venue: 3,
  },
  {
    first_name: 'Larry',
    last_name: 'Bishop',
    role_id: 12,
    primary_venue: 3,
  },
  {
    first_name: 'Kelly',
    last_name: 'Lucas',
    role_id: 12,
    primary_venue: 3,
  },
  {
    first_name: 'Landin',
    last_name: 'Love',
    role_id: 13,
    primary_venue: 3,
  },
  {
    first_name: 'Amara',
    last_name: 'Villanueva',
    role_id: 13,
    primary_venue: 3,
  },
  {
    first_name: 'Nathen',
    last_name: 'Pena',
    role_id: 13,
    primary_venue: 3,
  },
  {
    first_name: 'Gracie',
    last_name: 'Levine',
    role_id: 13,
    primary_venue: 3,
  },
  {
    first_name: 'Tamara',
    last_name: 'Hull',
    role_id: 13,
    primary_venue: 3,
  },
  {
    first_name: 'Kirsten',
    last_name: 'Reese',
    role_id: 13,
    primary_venue: 3,
  },
  {
    first_name: 'Yuliana',
    last_name: 'Rush',
    role_id: 13,
    primary_venue: 3,
  },
  {
    first_name: 'Harley',
    last_name: 'Cole',
    role_id: 13,
    primary_venue: 3,
  },
  {
    first_name: 'Haylie',
    last_name: 'Rush',
    role_id: 13,
    primary_venue: 3,
  },
  {
    first_name: 'Dylan',
    last_name: 'Brown',
    role_id: 13,
    primary_venue: 3,
  },
  {
    first_name: 'Alden',
    last_name: 'Mack',
    role_id: 14,
    primary_venue: 1,
  },
  {
    first_name: 'Sophie',
    last_name: 'Hale',
    role_id: 14,
    primary_venue: 1,
  },
  {
    first_name: 'Shaniya',
    last_name: 'Blair',
    role_id: 14,
    primary_venue: 1,
  },
  {
    first_name: 'Pedro',
    last_name: 'Keith',
    role_id: 14,
    primary_venue: 1,
  },
  {
    first_name: 'Joe',
    last_name: 'Boyd',
    role_id: 14,
    primary_venue: 1,
  },
  {
    first_name: 'Pedro',
    last_name: 'Horne',
    role_id: 14,
    primary_venue: 2,
  },
  {
    first_name: 'Abby',
    last_name: 'Mccall',
    role_id: 14,
    primary_venue: 2,
  },
  {
    first_name: 'Elliott',
    last_name: 'Mckenzie',
    role_id: 14,
    primary_venue: 2,
  },
  {
    first_name: 'Ray',
    last_name: 'Rowland',
    role_id: 14,
    primary_venue: 2,
  },
  {
    first_name: 'Marlie',
    last_name: 'Sandoval',
    role_id: 14,
    primary_venue: 2,
  },
  {
    first_name: 'Edgar',
    last_name: 'Green',
    role_id: 14,
    primary_venue: 2,
  },
  {
    first_name: 'Dulce',
    last_name: 'Dougherty',
    role_id: 14,
    primary_venue: 2,
  },
  {
    first_name: 'Milton',
    last_name: 'Parks',
    role_id: 14,
    primary_venue: 2,
  },
  {
    first_name: 'Sloane',
    last_name: 'Macias',
    role_id: 14,
    primary_venue: 3,
  },
  {
    first_name: 'Belinda',
    last_name: 'Webster',
    role_id: 14,
    primary_venue: 3,
  },
  {
    first_name: 'Kayleigh',
    last_name: 'Vasquez',
    role_id: 14,
    primary_venue: 3,
  },
  {
    first_name: 'Darryl',
    last_name: 'Farley',
    role_id: 14,
    primary_venue: 3,
  },
  {
    first_name: 'Marquise',
    last_name: 'Pope',
    role_id: 14,
    primary_venue: 3,
  },
  {
    first_name: 'Jessie',
    last_name: 'Osborn',
    role_id: 14,
    primary_venue: 3,
  },
  {
    first_name: 'Marilyn',
    last_name: 'Ortiz',
    role_id: 14,
    primary_venue: 3,
  },
  {
    first_name: 'Kailyn',
    last_name: 'Clements',
    role_id: 14,
    primary_venue: 3,
  },
  {
    first_name: 'Abigail',
    last_name: 'Calhoun',
    role_id: 14,
    primary_venue: 3,
  },
  {
    first_name: 'Craig',
    last_name: 'Roberson',
    role_id: 14,
    primary_venue: 3,
  },
  {
    first_name: 'Rene',
    last_name: 'Vaughan',
    role_id: 14,
    primary_venue: 3,
  },
  {
    first_name: 'Charlie',
    last_name: 'Meyer',
    role_id: 14,
    primary_venue: 3,
  },
  {
    first_name: 'Finley',
    last_name: 'Sanders',
    role_id: 14,
    primary_venue: 3,
  },
  {
    first_name: 'Kayley',
    last_name: 'Wall',
    role_id: 14,
    primary_venue: 3,
  },
  {
    first_name: 'Jasiah',
    last_name: 'Nixon',
    role_id: 15,
    primary_venue: 1,
  },
  {
    first_name: 'Brody',
    last_name: 'Morales',
    role_id: 15,
    primary_venue: 1,
  },
  {
    first_name: 'Justine',
    last_name: 'Ruiz',
    role_id: 15,
    primary_venue: 1,
  },
  {
    first_name: 'Jamison',
    last_name: 'Nash',
    role_id: 15,
    primary_venue: 1,
  },
  {
    first_name: 'Jake',
    last_name: 'Paul',
    role_id: 15,
    primary_venue: 1,
  },
  {
    first_name: 'Taniya',
    last_name: 'Mann',
    role_id: 15,
    primary_venue: 2,
  },
  {
    first_name: 'Ashlee',
    last_name: 'Moran',
    role_id: 15,
    primary_venue: 2,
  },
  {
    first_name: 'Carlie',
    last_name: 'Charles',
    role_id: 15,
    primary_venue: 2,
  },
  {
    first_name: 'Gunner',
    last_name: 'Schroeder',
    role_id: 15,
    primary_venue: 2,
  },
  {
    first_name: 'Makena',
    last_name: 'Allison',
    role_id: 15,
    primary_venue: 2,
  },
  {
    first_name: 'Carlie',
    last_name: 'Hernandez',
    role_id: 15,
    primary_venue: 2,
  },
  {
    first_name: 'Kate',
    last_name: 'Krause',
    role_id: 15,
    primary_venue: 2,
  },
  {
    first_name: 'Elianna',
    last_name: 'Vargas',
    role_id: 15,
    primary_venue: 2,
  },
  {
    first_name: 'Lydia',
    last_name: 'Roy',
    role_id: 15,
    primary_venue: 2,
  },
  {
    first_name: 'Paxton',
    last_name: 'Pitts',
    role_id: 15,
    primary_venue: 2,
  },
  {
    first_name: 'Bo',
    last_name: 'Robinson',
    role_id: 15,
    primary_venue: 2,
  },
  {
    first_name: 'Jimena',
    last_name: 'Morales',
    role_id: 15,
    primary_venue: 2,
  },
  {
    first_name: 'Danielle',
    last_name: 'Salinas',
    role_id: 15,
    primary_venue: 2,
  },
  {
    first_name: 'Hallie',
    last_name: 'Shelton',
    role_id: 15,
    primary_venue: 2,
  },
  {
    first_name: 'Camren',
    last_name: 'Rivera',
    role_id: 15,
    primary_venue: 2,
  },
  {
    first_name: 'Andreas',
    last_name: 'Molina',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Gabriela',
    last_name: 'Obrien',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Nick',
    last_name: 'Mccarthy',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Alvaro',
    last_name: 'Ryan',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Abigail',
    last_name: 'Strickland',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Reese',
    last_name: 'Watkins',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Porter',
    last_name: 'Conway',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Giada',
    last_name: 'Bolton',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Jaylen',
    last_name: 'Charles',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Darwin',
    last_name: 'Mayo',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Alan',
    last_name: 'Livingston',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Jerome',
    last_name: 'Benitez',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Terrell',
    last_name: 'Forbes',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Juliette',
    last_name: 'Short',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Camryn',
    last_name: 'Joseph',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Skye',
    last_name: 'Mcknight',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Noe',
    last_name: 'Randolph',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Aubrey',
    last_name: 'Russell',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Jaelyn',
    last_name: 'Weeks',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Frida',
    last_name: 'Mayer',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Harry',
    last_name: 'Church',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Mariam',
    last_name: 'Dickson',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Veronica',
    last_name: 'Stein',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Aria',
    last_name: 'Boyle',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Jaylyn',
    last_name: 'Burke',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Luciana',
    last_name: 'Gomez',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Juliet',
    last_name: 'Bass',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Maria',
    last_name: 'Smith',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Richard',
    last_name: 'Koch',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Presley',
    last_name: 'Sanchez',
    role_id: 15,
    primary_venue: 3,
  },
  {
    first_name: 'Jordin',
    last_name: 'Cantu',
    role_id: 16,
    primary_venue: 1,
  },
  {
    first_name: 'Princess',
    last_name: 'Jackson',
    role_id: 16,
    primary_venue: 1,
  },
  {
    first_name: 'Makenzie',
    last_name: 'Madden',
    role_id: 16,
    primary_venue: 2,
  },
  {
    first_name: 'Mattie',
    last_name: 'Combs',
    role_id: 16,
    primary_venue: 2,
  },
  {
    first_name: 'Addisyn',
    last_name: 'Garcia',
    role_id: 16,
    primary_venue: 2,
  },
  {
    first_name: 'Jamya',
    last_name: 'Shah',
    role_id: 16,
    primary_venue: 3,
  },
  {
    first_name: 'Frankie',
    last_name: 'Spencer',
    role_id: 16,
    primary_venue: 3,
  },
  {
    first_name: 'Shawn',
    last_name: 'Weeks',
    role_id: 16,
    primary_venue: 3,
  },
  {
    first_name: 'Zoie',
    last_name: 'Kane',
    role_id: 17,
    primary_venue: 1,
  },
  {
    first_name: 'Karson',
    last_name: 'Quinn',
    role_id: 17,
    primary_venue: 1,
  },
  {
    first_name: 'Jovan',
    last_name: 'Baxter',
    role_id: 17,
    primary_venue: 1,
  },
  {
    first_name: 'Elle',
    last_name: 'Chung',
    role_id: 17,
    primary_venue: 1,
  },
  {
    first_name: 'Sergio',
    last_name: 'Roach',
    role_id: 17,
    primary_venue: 2,
  },
  {
    first_name: 'Kasey',
    last_name: 'Schaefer',
    role_id: 17,
    primary_venue: 2,
  },
  {
    first_name: 'Alden',
    last_name: 'Nielsen',
    role_id: 17,
    primary_venue: 2,
  },
  {
    first_name: 'Wayne',
    last_name: 'Butler',
    role_id: 17,
    primary_venue: 2,
  },
  {
    first_name: 'Jaidyn',
    last_name: 'Lambert',
    role_id: 17,
    primary_venue: 2,
  },
  {
    first_name: 'Mackenzie',
    last_name: 'Phillips',
    role_id: 17,
    primary_venue: 2,
  },
  {
    first_name: 'Niko',
    last_name: 'Burch',
    role_id: 17,
    primary_venue: 3,
  },
  {
    first_name: 'Madeline',
    last_name: 'Mccoy',
    role_id: 17,
    primary_venue: 3,
  },
  {
    first_name: 'Dayami',
    last_name: 'Duke',
    role_id: 17,
    primary_venue: 3,
  },
  {
    first_name: 'Peter',
    last_name: 'Cole',
    role_id: 17,
    primary_venue: 3,
  },
  {
    first_name: 'Griffin',
    last_name: 'Pierce',
    role_id: 17,
    primary_venue: 3,
  },
  {
    first_name: 'Katherine',
    last_name: 'York',
    role_id: 17,
    primary_venue: 3,
  },
  {
    first_name: 'Jocelynn',
    last_name: 'Graham',
    role_id: 17,
    primary_venue: 3,
  },
  {
    first_name: 'Jessica',
    last_name: 'Gregory',
    role_id: 17,
    primary_venue: 3,
  },
  {
    first_name: 'Carlo',
    last_name: 'Frost',
    role_id: 17,
    primary_venue: 3,
  },
  {
    first_name: 'Derick',
    last_name: 'Marquez',
    role_id: 17,
    primary_venue: 3,
  },
];

const seedEmployees = () => Employee.bulkCreate(employeeData);

module.exports = seedEmployees;
